export const mappingProfilesData = [
  {
    id: '1737d899-6fb9-44f4-ba16-9a8b111cd61d',
    name: 'AP holdings-MARC Bib',
    description: 'Use for PurpleVendor approval plan MARC files',
    tags: {
      tagList: [
        'approvals',
        'purple-vendor',
      ],
    },
    outputFormat: 'MARC',
    recordTypes: ['HOLDINGS'],
    deleted: false,
    userInfo: {
      firstName: 'John',
      lastName: 'M',
      userName: 'john_m',
    },
    parentProfiles: [],
    childProfiles: [],
    metadata: {
      createdDate: '2018-12-02T09:05:30.000+0000',
      createdByUserId: '',
      createdByUsername: '',
      updatedDate: '2018-12-04T09:05:30.000+0000',
      updatedByUserId: '',
      updatedByUsername: '',
    },
  }, {
    id: '4a887936-794d-4014-a1ec-046abfab01f6',
    name: 'AP Instance',
    description: 'Use for PurpleVendor approval plan MARC files',
    tags: {
      tagList: [
        'approvals',
        'purple-vendor',
      ],
    },
    outputFormat: 'MARC',
    recordTypes: ['INSTANCE'],
    deleted: false,
    userInfo: {
      firstName: 'Mark',
      lastName: 'D',
      userName: 'dmark',
    },
    parentProfiles: [],
    childProfiles: [],
    metadata: {
      createdDate: '2018-11-03T11:22:30.000+0000',
      createdByUserId: '',
      createdByUsername: '',
      updatedDate: '2018-11-04T11:22:30.000+0000',
      updatedByUserId: '',
      updatedByUsername: '',
    },
  }, {
    id: '2c655027-83ee-40e9-8221-d252c9bf7b65',
    name: 'AP item from MARC',
    description: 'Use for PurpleVendor approval plan MARC files',
    tags: {
      tagList: [
        'approvals',
        'purple-vendor',
      ],
    },
    outputFormat: 'MARC',
    recordTypes: ['ITEM'],
    deleted: false,
    userInfo: {
      firstName: 'Block',
      lastName: 'Madyson',
      userName: 'block_m',
    },
    parentProfiles: [],
    childProfiles: [],
    metadata: {
      createdDate: '2018-12-03T11:45:21.000+0000',
      createdByUserId: '',
      createdByUsername: '',
      updatedDate: '2018-12-07T11:45:21.000+0000',
      updatedByUserId: '',
      updatedByUsername: '',
    },
  }, {
    id: 'c5bccf59-cb5f-4edf-95a1-5dae28d75747',
    name: 'Brief MARC Bib from MARC',
    description: 'Create new MARC bib - brief',
    tags: { tagList: [] },
    outputFormat: 'MARC',
    recordTypes: ['ITEM', 'HOLDINGS'],
    deleted: false,
    userInfo: {
      firstName: 'Denis',
      lastName: 'Lewis',
      userName: 'denis_l',
    },
    parentProfiles: [],
    childProfiles: [],
    metadata: {
      createdDate: '2018-12-03T11:45:21.000+0000',
      createdByUserId: '',
      createdByUsername: '',
      updatedDate: '2018-12-07T11:45:21.000+0000',
      updatedByUserId: '',
      updatedByUsername: '',
    },
  },
];
